### ISSUE TITLE
Metric count alerts fail with "invalid character '}' looking for beginning of object key string"

### ISSUE THREAD

**Issue by idastambuk** [grafana/opensearch-datasource#204]
**What happened**:

Opening this ticket to track a bug reported in a comment from [here](https://github.com/grafana/opensearch-datasource/issues/173#issuecomment-1591204366). 
The original bug was fixed in 2.6.1 and had a different error message, so this looks like a different bug. Pasting here what the comment said: 

> Everything is fine while creating the alert, but a few times a day, we receive a notification for a datasourceError, and the Error annotation says [plugin.downstreamError] failed to query data: Failed to query data: rpc error: code = Unknown desc = error while Decoding to MultiSearchResponse: invalid character '}' looking for beginning of object key string.
At first we were running v2.4.1, I upgraded to 2.6.2 after seeing this thread but nothing changed.

From this [comment](https://github.com/grafana/opensearch-datasource/issues/173#issuecomment-1591801365), the query doesn't fail when setting up the alert which is strange, since it doesn't look exactly like a clear a FE - BE problem? 
![245898091-2a919e08-532a-4771-b83b-e9b69fdf5439](https://github.com/grafana/opensearch-datasource/assets/16140639/fcd5336f-0bfc-4a9b-9d86-12f228553c6a)

Theres more useful info in the original issue. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Plugin version:

**Comment by pavriet-boxtal** [comment]
Hello @idastambuk,

Unfortunately, I was not able to find any other error types. I took a look at the grafana logs but nothing relevant.

**Comment by iwysiu** [comment]
Still investigating, but initial findings: I haven't been able to repro it, but I did look into it.
The `invalid character '}' looking for beginning of object key string` error comes from the [json package](https://github.com/grafana/opensearch-datasource/blob/34a4fdd68a4bb022e1b8ef625ea639f1f0e65769/pkg/opensearch/client/client.go#L358), and it's associated with malformed json objects. The datasource is parsing the response without editing it, so it shouldn't be an issue introduced there. There's a stackoverflow post for a [very old version of Elasticsearch](https://stackoverflow.com/questions/28101390/elasticsearch-returning-invalid-json) with a similar issue, though having followed the issue links, it was fixed a long time ago and I doubt it's the same.
I wonder if there’s a subtle difference between the typescript json parsing (for the panel) and the go json parsing (for the alert) where one is getting tripped up and the other isn’t. It's also interesting that it only happens sometimes.

**Comment by sarahzinger** [comment]
@pavriet-boxtal just trying to make sure we capture all of the repro steps:

In looking at your comments it sounds like you're running opensearch 1.3 from AWS opensearch service, but when you run "get version and save" you're getting back "ES 7.10.2" is that correct? @iwysiu sounds like there is a separate issue here related to version detection right? Is this a known/documented issue?

**Comment by pavriet-boxtal** [comment]
Hello @sarahzinger

Yes, I confirm opensearch 1.3 from AWS
![image](https://github.com/grafana/opensearch-datasource/assets/136579429/db57ec7e-fed8-4844-8837-2867c8174061)

I tried clicking the 'get version and save' button while watching network traffic (in the browser f12 menu) and found that:

```json
  "version" : {
    "number" : "7.10.2",
    "build_type" : "tar",
    "build_hash" : "unknown",
    "build_date" : "2023-03-22T11:53:34.141437Z",
    "build_snapshot" : false,
    "lucene_version" : "8.10.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  }
```
So it's probably not an issue on your side :)

**Comment by sarahzinger** [comment]
@pavriet-boxtal thanks for that! We've opened an issue for version detection [here](https://github.com/grafana/opensearch-datasource/issues/206), just to track it, but we agree, it seems we're just forwarding misinformation from aws. 

It does seem likely that maybe this version issue is separate and disconnected from your original issue as you say you were seeing the invalid character error in 2.4.1 before version detection was released, yes? 

It seems like perhaps next steps are to add some better logs [here](https://github.com/grafana/opensearch-datasource/blob/34a4fdd68a4bb022e1b8ef625ea639f1f0e65769/pkg/opensearch/client/client.go#L358) to understand what is going wrong with the decoding. Will move this to next

**Comment by pavriet-boxtal** [comment]
@sarahzinger I agree the version issue seems separate from this thread.

I confirm I had the same errors with v2.4.1.

We are not fully committed to grafana 9 (we still have a separate grafana 8). So I am ok if you want me to run a special version of the plugin with loads of logs.

**Comment by pavriet-boxtal** [comment]
Hello @sarahzinger @idastambuk,

Hope you are doing well. Any news on the issue ?

Regards

**Comment by sarahzinger** [comment]
@pavriet-boxtal we've moved this ticket into "next" so we plan to take a look at it in an upcoming sprint! If you find any more repro steps that will help!

**Comment by katebrenner** [comment]
@pavriet-boxtal we could not reproduce this issue - could you let us know if you're still experiencing this issue with the latest version of the OpenSearch plugin (2.15.3)?

**Comment by pavriet-boxtal** [comment]
Hello, we replaced the plugin with the elasticsearch one a while back. We strongly suspect it was the culprit of another issue (full server crash).

So I have no idea
